### PR TITLE
Use Makefile.COMMON for building statsd_bridge.

### PR DESCRIPTION
**Pull request by juliusv**

### CODE REVIEW

**Comment by juliusv** [comment]
@grobie

**Comment by grobie** [comment]
We should add a prominent banner to the Makefile.COMMON files explaining that they should not be touched and that the original file is in prometheus/utils.

**Comment by juliusv** [comment]
@grobie Like this? https://github.com/prometheus/utils/pull/4

It's also a bit annoying that one needs to manually update the app repos after any chances there... would be great to get some automated propagation going (but yeah, so many other things to do)...

**Comment by juliusv** [comment]
Updated the Makefile.COMMON here too.

**Comment by juliusv** [comment]
I can haz :+1:?

**Comment by juliusv** [comment]
Merging for now...

**Comment by grobie** [comment]
:+1: sry

**Pull request merged**
